export const sampleNodesData: { name: string, properties: { city: string, language: string, team: string } }[] = [
    { name: "Ava", properties: { city: "New York", language: "English", team: "Bulls" } },
    { name: "Liam", properties: { city: "New York", language: "English", team: "Bulls" } },
    { name: "Olivia", properties: { city: "New York", language: "Spanish", team: "Sharks" } },
    { name: "Noah", properties: { city: "London", language: "English", team: "Bulls" } },
    { name: "Emma", properties: { city: "London", language: "English", team: "Bulls" } },
    { name: "Haruto", properties: { city: "Tokyo", language: "Japanese", team: "Sharks" } },
    { name: "Yui", properties: { city: "Tokyo", language: "Japanese", team: "Sharks" } },
    { name: "Louis", properties: { city: "Paris", language: "French", team: "Bulls" } },
    { name: "Camille", properties: { city: "Paris", language: "French", team: "Bulls" } },
    { name: "Ben", properties: { city: "Berlin", language: "German", team: "Sharks" } },
    { name: "Hanna", properties: { city: "Berlin", language: "German", team: "Sharks" } },
    { name: "Mei", properties: { city: "Tokyo", language: "Japanese", team: "Sharks" } },
    { name: "Lucas", properties: { city: "Paris", language: "French", team: "Bulls" } },
    { name: "Isabella", properties: { city: "New York", language: "Spanish", team: "Sharks" } },
    { name: "Mason", properties: { city: "London", language: "English", team: "Bulls" } },
    { name: "Sophia", properties: { city: "New York", language: "English", team: "Sharks" } },
    { name: "Finn", properties: { city: "Berlin", language: "German", team: "Sharks" } },
    { name: "Chloe", properties: { city: "Paris", language: "French", team: "Bulls" } },
    { name: "Rin", properties: { city: "Tokyo", language: "Japanese", team: "Sharks" } },
    { name: "Arthur", properties: { city: "London", language: "English", team: "Bulls" } },
];
